### ISSUE TITLE
This is disgusting.

### ISSUE THREAD

**Issue by dlmather** [kgryte/utils-platform#2]
Why Athan?

**Comment by johndvorakHR** [comment]
Coming soon:

@kgryte/utils-require

``` node
'use strict';

// EXPORTS //

module.exports = global.require;
```

**Comment by dlmather** [comment]
![3ui2mml](https://cloud.githubusercontent.com/assets/1505373/10774256/5c126592-7cbd-11e5-86fe-a2f0838a0434.gif)

**Comment by kgryte** [comment]
Answered in #1.
