### ISSUE TITLE
Converage report is falsified

### ISSUE THREAD

**Issue by dlmather** [kgryte/utils-platform#3]
![1yyu2zc](https://cloud.githubusercontent.com/assets/1505373/10774215/2304d212-7cbd-11e5-993b-d20caf20c497.gif)

**Comment by johndvorakHR** [comment]
that is legit
https://codecov.io/github/kgryte/utils-platform/lib/index.js?ref=675d350c71f010aa280b9c87c88efc6e25acc649

100%!!

**Comment by kgryte** [comment]
Addressed in #1.
